import {
  DEFAULT_PERSONAL_BUDGET_CATEGORIES,
  DEFAULT_BUSINESS_BUDGET_CATEGORIES,
  BUDGET_CATEGORY_ALIASES,
} from "./budget";

export const DEFAULT_CATEGORIES = [
  ...DEFAULT_PERSONAL_BUDGET_CATEGORIES,
  ...DEFAULT_BUSINESS_BUDGET_CATEGORIES,
] as const;

export const LEGACY_CATEGORY_ALIASES = BUDGET_CATEGORY_ALIASES;
